// <auto-generated />
namespace Emlak_Yorumlari.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class appendquestionmigrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appendquestionmigrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202107260914532_append-question-migrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
